# Generated by Django 5.1.4 on 2025-05-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline', models.CharField(max_length=255)),
                ('Price', models.FloatField()),
                ('Start_Day', models.DateField()),
                ('Start_time', models.TimeField()),
                ('take_place', models.CharField(max_length=255)),
                ('End_time', models.TimeField()),
                ('destination', models.CharField(max_length=255)),
                ('flight_time', models.DurationField()),
                ('transit', models.CharField(max_length=255)),
                ('total_time_hour', models.FloatField()),
                ('End_day', models.DateField()),
                ('Is_Transit', models.BooleanField()),
                ('Is_VietJet_Air', models.BooleanField()),
                ('Is_Vietnam_Airlines', models.BooleanField()),
                ('Is_Bamboo_Airways', models.BooleanField()),
                ('Is_Vietravel_Airlines', models.BooleanField()),
                ('Id_Plane', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('score_hotels', models.FloatField()),
                ('number_rating', models.IntegerField()),
                ('star_number', models.IntegerField()),
                ('received_time', models.DateTimeField()),
                ('giveback_time', models.DateTimeField()),
                ('from_center', models.FloatField()),
                ('popular_destination', models.CharField(max_length=255)),
                ('hotel_link', models.URLField()),
                ('hotel_city', models.CharField(max_length=255)),
                ('hotel_id', models.CharField(max_length=50, unique=True)),
                ('start_clean', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('duration', models.DurationField()),
                ('rating', models.FloatField()),
                ('City', models.CharField(max_length=255)),
                ('tour_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
