# Generated by Django 5.1.4 on 2025-05-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='number_rating',
            field=models.FloatField(),
        ),
    ]
