# Generated by Django 5.1.4 on 2025-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0002_alter_hotel_number_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='End_day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='End_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Start_Day',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Start_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='giveback_time',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='received_time',
            field=models.CharField(max_length=255),
        ),
    ]
