# Generated by Django 5.1.4 on 2025-05-19 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0003_alter_flight_end_day_alter_flight_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='from_center',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='number_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='score_hotels',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
