# Generated by Django 5.1.4 on 2025-05-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_alter_hotel_from_center_alter_hotel_number_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='from_center',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
