# Generated by Django 5.1.4 on 2025-05-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0005_alter_hotel_from_center'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='score_hotels',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
