# Generated by Django 5.1.4 on 2025-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0006_alter_hotel_score_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='total_time_hour',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
