# Generated by Django 5.1.4 on 2025-05-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0007_alter_flight_flight_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
