# Generated by Django 5.1.4 on 2025-05-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0008_alter_flight_flight_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='rating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
